# Generated by Django 4.2.7 on 2025-12-09 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('pending_self', 'Pending Self-Assessment'), ('pending_manager', 'Pending Manager Review'), ('pending_peer', 'Pending Peer Feedback'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('draft', 'Draft')], default='pending_self', max_length=20)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('salary_increase_recommended', models.BooleanField(default=False)),
                ('improvement_plan_required', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishments', models.TextField(help_text='Key achievements during review period')),
                ('challenges_faced', models.TextField(blank=True, help_text='Challenges encountered')),
                ('skills_developed', models.TextField(blank=True, help_text='New skills learned')),
                ('quality_of_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('productivity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('teamwork', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('initiative', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('goals_achieved', models.TextField(help_text='Goals achieved from previous review')),
                ('goals_for_next_period', models.TextField(help_text='Goals for next review period')),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessment', to='hr_reviews.review')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Q4 2025 Performance Review'", max_length=200)),
                ('review_type', models.CharField(choices=[('annual', 'Annual Review'), ('semi_annual', 'Semi-Annual Review'), ('quarterly', 'Quarterly Review'), ('probation', 'Probation Review')], default='quarterly', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(help_text='Review period start date')),
                ('end_date', models.DateField(help_text='Review period end date')),
                ('self_review_deadline', models.DateField(help_text='Deadline for self-assessment')),
                ('manager_review_deadline', models.DateField(help_text='Deadline for manager reviews')),
                ('peer_review_deadline', models.DateField(blank=True, help_text='Optional peer review deadline', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_cycles', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(help_text='Employees included in this review cycle', related_name='review_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hr_reviews.reviewcycle'),
        ),
        migrations.AddField(
            model_name='review',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='Manager/Reviewer assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PeerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_feedback', models.TextField(help_text='Feedback on collaboration')),
                ('strengths', models.TextField(help_text='Observed strengths')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Suggested improvements')),
                ('teamwork', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('helpfulness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('additional_comments', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True, help_text='Hide peer identity from employee')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer', models.ForeignKey(help_text='Colleague providing feedback', on_delete=django.db.models.deletion.CASCADE, related_name='peer_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_feedbacks', to='hr_reviews.review')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_summary', models.TextField(help_text='Overall performance summary')),
                ('strengths', models.TextField(help_text='Employee strengths')),
                ('areas_for_improvement', models.TextField(help_text='Areas needing improvement')),
                ('quality_of_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('productivity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('teamwork', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('initiative', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('leadership', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('problem_solving', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('goals_achievement_comment', models.TextField(help_text='Comment on goal achievement')),
                ('goals_for_next_period', models.TextField(help_text='Goals set for next period')),
                ('promotion_recommendation', models.BooleanField(default=False)),
                ('salary_increase_recommendation', models.BooleanField(default=False)),
                ('training_recommendations', models.TextField(blank=True, help_text='Recommended training/development')),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('manager_comments', models.TextField(blank=True, help_text='Additional manager comments')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_review', to='hr_reviews.review')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewcycle',
            index=models.Index(fields=['status', 'start_date'], name='hr_reviews__status_20f099_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcycle',
            index=models.Index(fields=['self_review_deadline'], name='hr_reviews__self_re_b16e87_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['employee', 'status'], name='hr_reviews__employe_537c85_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['cycle', 'status'], name='hr_reviews__cycle_i_05e85e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('cycle', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='peerfeedback',
            unique_together={('review', 'peer')},
        ),
    ]
