# Generated by Django 4.2.7 on 2025-11-01 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Employees/Interns assigned to this project', related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
