# Generated by Django 4.2.7 on 2025-11-01 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval_level',
            field=models.IntegerField(default=1, help_text='1=Manager, 2=Department Head, 3=HR'),
        ),
        migrations.AddField(
            model_name='leave',
            name='approval_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='current_approval_level',
            field=models.IntegerField(default=1, help_text='Current stage in approval hierarchy'),
        ),
        migrations.AddField(
            model_name='leave',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='requires_multi_level',
            field=models.BooleanField(default=False, help_text='True if leave requires multi-level approval (e.g., > 5 days)'),
        ),
        migrations.AddField(
            model_name='leave',
            name='secondary_approver',
            field=models.ForeignKey(blank=True, help_text='Secondary approver (for multi-level approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='applied_to',
            field=models.ForeignKey(blank=True, help_text='Primary approver (usually direct manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
