# Generated by Django 4.2.7 on 2025-11-19 01:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('individual', 'Individual Goal'), ('team', 'Team Goal'), ('department', 'Department Goal'), ('company', 'Company Goal')], default='individual', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Overall progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Target value (e.g., revenue, units, etc.)', max_digits=12, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current achieved value', max_digits=12)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., USD, units, hours)', max_length=50)),
                ('is_okr', models.BooleanField(default=False, help_text='Is this an OKR (Objective and Key Results)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Team members assigned to this goal', related_name='assigned_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Goal Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hr_performance.goal')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hr_performance.goalcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='hr_performance.goalcategory'),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(help_text='Primary owner of the goal', on_delete=django.db.models.deletion.CASCADE, related_name='owned_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, help_text='Parent objective (for key results)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='hr_performance.goal'),
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(help_text='Progress percentage at this update', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current achieved value', max_digits=12, null=True)),
                ('title', models.CharField(help_text='Brief title of the update', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of progress')),
                ('challenges', models.TextField(blank=True, help_text='Any challenges or blockers faced')),
                ('help_needed', models.BooleanField(default=False, help_text='Does this goal need help?')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='performance/progress/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='hr_performance.goal')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['goal', 'created_at'], name='hr_performa_goal_id_e7340d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hr_performance.goal')),
            ],
            options={
                'ordering': ['order', 'due_date'],
                'indexes': [models.Index(fields=['goal', 'status'], name='hr_performa_goal_id_ffd10b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('threshold_low', models.DecimalField(decimal_places=2, help_text='Below this is poor performance', max_digits=12)),
                ('threshold_medium', models.DecimalField(decimal_places=2, help_text='Above this is good performance', max_digits=12)),
                ('threshold_high', models.DecimalField(decimal_places=2, help_text='Above this is excellent performance', max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='hr_performance.goalcategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='hr_performance.goal')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='hr_performa_owner_i_9dbac8_idx'), models.Index(fields=['period_end'], name='hr_performa_period__91764d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner', 'status'], name='hr_performa_owner_i_f12eec_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['due_date'], name='hr_performa_due_dat_651e27_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['goal_type', 'status'], name='hr_performa_goal_ty_eab8d5_idx'),
        ),
    ]
