# Generated by Django 4.2.7 on 2025-10-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_day6_project_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('overdue', 'Task Overdue'), ('critical_priority', 'Critical Priority'), ('blocked', 'Task Blocked'), ('manual', 'Manual Escalation')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('escalated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_created', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations_received', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='dashboard.task')),
            ],
            options={
                'verbose_name': 'Task Escalation',
                'verbose_name_plural': 'Task Escalations',
                'db_table': 'task_escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_due_soon', models.BooleanField(default=True)),
                ('email_task_overdue', models.BooleanField(default=True)),
                ('email_task_completed', models.BooleanField(default=False)),
                ('email_task_escalated', models.BooleanField(default=True)),
                ('email_project_update', models.BooleanField(default=True)),
                ('email_milestone_reached', models.BooleanField(default=True)),
                ('email_announcement', models.BooleanField(default=True)),
                ('inapp_task_assigned', models.BooleanField(default=True)),
                ('inapp_task_due_soon', models.BooleanField(default=True)),
                ('inapp_task_overdue', models.BooleanField(default=True)),
                ('inapp_task_completed', models.BooleanField(default=True)),
                ('inapp_task_escalated', models.BooleanField(default=True)),
                ('inapp_project_update', models.BooleanField(default=True)),
                ('inapp_milestone_reached', models.BooleanField(default=True)),
                ('inapp_announcement', models.BooleanField(default=True)),
                ('reminder_hours_before_due', models.IntegerField(default=24, help_text='Hours before due date to send reminder')),
                ('digest_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='realtime', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_due_soon', 'Task Due Soon'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('task_escalated', 'Task Escalated'), ('project_update', 'Project Update'), ('milestone_reached', 'Milestone Reached'), ('announcement', 'Announcement'), ('system', 'System Notification')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_in_app', models.BooleanField(default=True)),
                ('sent_push', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
